---
language: php

php: "7.1"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$TMPDIR/phpstan/cache"

env:
  global:
    - ORCA_SUT_NAME=acquia/headless_lightning
    - ORCA_SUT_BRANCH=master
    - ORCA_VERSION=v1.0.0-alpha18
    - ORCA_PACKAGES_CONFIG_ALTER=../headless_lightning/tests/packages_alter.yml
    - ORCA_FIXTURE_PROFILE=headless_lightning

matrix:
  fast_finish: true
  include:
    # Standard ORCA jobs.
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    - { name: "Deprecated code scan", env: ORCA_JOB=DEPRECATED_CODE_SCAN_SUT }
    - { name: "Isolated test w/ recommended package versions", env: ORCA_JOB=ISOLATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions", env: ORCA_JOB=INTEGRATED_RECOMMENDED }
    # The previous version of Drupal Core at any time is not currently
    # supported.
    # - { name: "Integrated test w/ recommended package versions & previous minor release of Drupal core", env: ORCA_JOB=CORE_PREVIOUS }
    - { name: "Isolated test w/ dev package versions", env: ORCA_JOB=ISOLATED_DEV }
    - { name: "Integrated test w/ dev package versions", env: ORCA_JOB=INTEGRATED_DEV }
    - { name: "Integrated test w/ dev package versions & next minor dev version of Drupal core", env: ORCA_JOB=CORE_NEXT }
    # Custom job.
    - { name: "Upgrade test", env: DB_FIXTURE=1.2.0-alpha1 }
  allow_failures:
    - env: ORCA_JOB=ISOLATED_DEV
    - env: ORCA_JOB=INTEGRATED_DEV
    - env: ORCA_JOB=CORE_NEXT
    # Temporary allowances.
    - env: ORCA_JOB=STATIC_CODE_ANALYSIS

before_install:
  - git clone --branch ${ORCA_VERSION} --depth 1 https://github.com/acquia/orca.git ../orca
  - ../orca/bin/travis/before_install.sh

install:
  - ../orca/bin/travis/install.sh
  - ./tests/travis/install.sh

before_script: ../orca/bin/travis/before_script.sh

script:
  - ../orca/bin/travis/script.sh
  - ./tests/travis/script.sh

before_cache: ../orca/bin/travis/before_cache.sh

after_success: ../orca/bin/travis/after_success.sh

after_failure: ../orca/bin/travis/after_failure.sh

after_script: ../orca/bin/travis/after_script.sh
