# This file is used by Acquia Pipelines continuous integration. It builds
# Headless Lightning and runs its functional tests. Upon success, an artifact is
# deployed to the headlessnightly (f9b2254c-024f-4a28-bc14-fc1c06a495a6) sub on
# Acquia cloud.
version: 1.0.0
services:
  - mysql

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/bin:$PATH"
            - composer validate --no-check-all --ansi
            - composer install
      - install:
          type: script
          script:
            - cd $SOURCE_DIR
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - phing install -Ddb.password=root -Ddb.database=drupal -Durl=http://127.0.0.1:8080
      - test:
          type: script
          script:
            - cd $SOURCE_DIR/docroot
            - drush runserver --default-server=builtin 8080 &>/dev/null &
            - sleep 10
            - phpunit --configuration ./core --group headless
            - behat --stop-on-failure --config ./sites/default/files/behat.yml --tags=headless --tags=~javascript
      - cleanup:
          type: script
          script:
            # Setup settings file and codebase with minimum required for cloud.
            - cd $SOURCE_DIR
            - phing cloud-settings
